# Generated by Django 5.2.6 on 2025-09-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posttype_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='annonymouse',
            new_name='annonymous',
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.post')),
            ],
        ),
    ]
