# Generated by Django 5.2.6 on 2025-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
