# Generated by Django 5.2.6 on 2025-09-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pending',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='profile/profile.png', null=True, upload_to='profile/'),
        ),
    ]
